""" --------------------------------------------------------------------------
 Business   | Asesores y Consultores en Tecnología S.A. de C.V.
 Programmer | Dyanko Cisneros Mendoza
 Customer   | Human Quality
 Project    | Mixed Room
 Version    | 0.1 --------------------------------------------------------- """

## CONTROL SCRIPT IMPORT ------------------------------------------------------
from extronlib.device import UIDevice
from extronlib.ui import Button, Label, Level
from extronlib.system import MESet

# UI Device
TLPM = UIDevice('TouchPanelM')
TLP1 = UIDevice('TouchPanelA')
TLP2 = UIDevice('TouchPanelB')
TLP3 = UIDevice('TouchPanelC')

# UI Buttons
BTN = {
    ## PANEL M ----------------------------------------
    ## Page Index
    'M_Index'   : Button(TLPM, 1),
    ## Page Room M - PIN
    'M_Pin0'    : Button(TLPM, 1000),
    'M_Pin1'    : Button(TLPM, 1001),
    'M_Pin2'    : Button(TLPM, 1002),
    'M_Pin3'    : Button(TLPM, 1003),
    'M_Pin4'    : Button(TLPM, 1004),
    'M_Pin5'    : Button(TLPM, 1005),
    'M_Pin6'    : Button(TLPM, 1006),
    'M_Pin7'    : Button(TLPM, 1007),
    'M_Pin8'    : Button(TLPM, 1008),
    'M_Pin9'    : Button(TLPM, 1009),
    'M_PinD'    : Button(TLPM, 1010, repeatTime=0.1),
    'M_PinX'    : Button(TLPM, 1011),
    ## Page Room M - Main Individual
    'M_Config'  : Button(TLPM, 400),
    ## Page Room M - Main Individual
    'M_Mode1'   : Button(TLPM, 401),
    'M_Mode2'   : Button(TLPM, 402),
    'M_Mode3'   : Button(TLPM, 403),
    ## Page Room M - Video
    'M_VHDMI'   : Button(TLPM, 31),
    'M_VShare'  : Button(TLPM, 32),
    'M_Signal1' : Button(TLPM, 33),
    'M_Signal2' : Button(TLPM, 34),
    'M_VPwrOn'  : Button(TLPM, 35),
    'M_VPwrOff' : Button(TLPM, 36),
    'M_Up'      : Button(TLPM, 37),
    'M_Stop'    : Button(TLPM, 38),
    'M_Down'    : Button(TLPM, 39),
    ## Page Room M - Audio
    'M_VolLess' : Button(TLPM, 41, repeatTime=0.1),
    'M_VolPlus' : Button(TLPM, 42, repeatTime=0.1),
    'M_Mute'    : Button(TLPM, 43),
    ## Page Room M - Lights & Blinds
    'M_Light1'  : Button(TLPM, 51),
    'M_Light2'  : Button(TLPM, 52),
    'M_Light3'  : Button(TLPM, 53),
    'M_Light4'  : Button(TLPM, 54),
    'M_BUp'     : Button(TLPM, 55),
    'M_BStop'   : Button(TLPM, 56),
    'M_BDown'   : Button(TLPM, 57),
    ## Page Room M - PowerOff
    'M_PwrAll'  : Button(TLPM, 61, holdTime=3),
    ## Page Room M - Main Full
    'M_FVideo'  : Button(TLPM, 111),
    'M_FAudio'  : Button(TLPM, 112),
    'M_FLights' : Button(TLPM, 113),
    'M_VoIP'    : Button(TLPM, 114),
    'M_FPwrOff' : Button(TLPM, 115),
    'M_FRoomA'  : Button(TLPM, 122),
    'M_FRoomB'  : Button(TLPM, 123),
    'M_FRoomC'  : Button(TLPM, 124),
    'M_Somfy'   : Button(TLPM, 125),
    'M_Lutron'  : Button(TLPM, 126),
    'M_Tesira'  : Button(TLPM, 127),
    'M_Matrix'  : Button(TLPM, 128),
    'M_Devio1'  : Button(TLPM, 129),
    'M_Devio2'  : Button(TLPM, 130),
    'M_Devio3'  : Button(TLPM, 131),
    'M_SW4HD1'  : Button(TLPM, 132),
    'M_SW4HD2'  : Button(TLPM, 133),
    'M_SW4HD3'  : Button(TLPM, 134),
    ## Page Room M - Video Full
    'M_ProjA'   : Button(TLPM, 141),
    'M_ProjB'   : Button(TLPM, 142),
    'M_ProjC'   : Button(TLPM, 143),
    'M_ProjD'   : Button(TLPM, 144),
    'M_ProjM'   : Button(TLPM, 145),
    ## Page Room M - Video Proj A Full
    'M_P1HDMI'    : Button(TLPM, 151),
    'M_P1Share'   : Button(TLPM, 152),
    'M_P1Signal1' : Button(TLPM, 153),
    'M_P1Signal2' : Button(TLPM, 154),
    'M_P1PwrOn'   : Button(TLPM, 155),
    'M_P1PwrOff'  : Button(TLPM, 156),
    'M_P1Up'      : Button(TLPM, 157),
    'M_P1Stop'    : Button(TLPM, 158),
    'M_P1Down'    : Button(TLPM, 159),
    'M_P1Back'    : Button(TLPM, 160),
    ## Page Room M - Video Proj B Full
    'M_P2HDMI'    : Button(TLPM, 161),
    'M_P2Share'   : Button(TLPM, 162),
    'M_P2Signal1' : Button(TLPM, 163),
    'M_P2Signal2' : Button(TLPM, 164),
    'M_P2PwrOn'   : Button(TLPM, 165),
    'M_P2PwrOff'  : Button(TLPM, 166),
    'M_P2Up'      : Button(TLPM, 167),
    'M_P2Stop'    : Button(TLPM, 168),
    'M_P2Down'    : Button(TLPM, 169),
    'M_P2Back'    : Button(TLPM, 170),
    ## Page Room M - Video Proj C Full
    'M_P3HDMI'    : Button(TLPM, 171),
    'M_P3Share'   : Button(TLPM, 172),
    'M_P3Signal1' : Button(TLPM, 173),
    'M_P3Signal2' : Button(TLPM, 174),
    'M_P3PwrOn'   : Button(TLPM, 175),
    'M_P3PwrOff'  : Button(TLPM, 176),
    'M_P3Up'      : Button(TLPM, 177),
    'M_P3Stop'    : Button(TLPM, 178),
    'M_P3Down'    : Button(TLPM, 179),
    'M_P3Back'    : Button(TLPM, 180),
    ## Page Room M - Video Proj D Full
    'M_P4HDMI'    : Button(TLPM, 181),
    'M_P4Share'   : Button(TLPM, 182),
    'M_P4Signal1' : Button(TLPM, 183),
    'M_P4Signal2' : Button(TLPM, 184),
    'M_P4PwrOn'   : Button(TLPM, 185),
    'M_P4PwrOff'  : Button(TLPM, 186),
    'M_P4Up'      : Button(TLPM, 187),
    'M_P4Stop'    : Button(TLPM, 188),
    'M_P4Down'    : Button(TLPM, 189),
    'M_P4Back'    : Button(TLPM, 190),
    ## Page Room M - Video Proj All Full
    'M_PMHDMI'    : Button(TLPM, 191),
    'M_PMSignal1' : Button(TLPM, 192),
    'M_PMShare'   : Button(TLPM, 193),
    'M_PMSignal2' : Button(TLPM, 194),
    'M_PMUp'      : Button(TLPM, 195),
    'M_PMStop'    : Button(TLPM, 196),
    'M_PMDown'    : Button(TLPM, 197),
    'M_PMBack'    : Button(TLPM, 198),
    ## Page Room M - Audio Full
    'M_.HDMI'     : Button(TLPM, 201),
    'M_.Signal1'  : Button(TLPM, 202),
    'M_.Share'    : Button(TLPM, 203),
    'M_.Signal2'  : Button(TLPM, 204),
    'M_.VolLess'  : Button(TLPM, 205, repeatTime=0.1),
    'M_.VolPlus'  : Button(TLPM, 206, repeatTime=0.1),
    'M_.MuteSpk'  : Button(TLPM, 208),
    'M_.MuteMiM'  : Button(TLPM, 209),
    'M_.MuteMiT'  : Button(TLPM, 210),
    ## Page Room M - Lights Full
    'M_LightA'    : Button(TLPM, 211),
    'M_LightB'    : Button(TLPM, 212),
    'M_LightC'    : Button(TLPM, 213),
    'M_LightM'    : Button(TLPM, 214),
    ## Page Room M - Lights & Blinds Full
    'M_ALight1'  : Button(TLPM, 221),
    'M_ALight2'  : Button(TLPM, 222),
    'M_ALight3'  : Button(TLPM, 223),
    'M_ALight4'  : Button(TLPM, 224),
    'M_ABUp'     : Button(TLPM, 225),
    'M_ABStop'   : Button(TLPM, 226),
    'M_ABDown'   : Button(TLPM, 227),
    ## Page Room B - Lights & Blinds Full
    'M_BLight1'  : Button(TLPM, 231),
    'M_BLight2'  : Button(TLPM, 232),
    'M_BLight3'  : Button(TLPM, 233),
    'M_BLight4'  : Button(TLPM, 234),
    'M_BBUp'     : Button(TLPM, 235),
    'M_BBStop'   : Button(TLPM, 236),
    'M_BBDown'   : Button(TLPM, 237),
    ## Page Room C - Lights & Blinds Full
    'M_CLight1'  : Button(TLPM, 241),
    'M_CLight2'  : Button(TLPM, 242),
    'M_CLight3'  : Button(TLPM, 243),
    'M_CLight4'  : Button(TLPM, 244),
    'M_CBUp'     : Button(TLPM, 245),
    'M_CBStop'   : Button(TLPM, 246),
    'M_CBDown'   : Button(TLPM, 247),
    ## Page Room M - Lights & Blinds Full
    'M_MLight1'  : Button(TLPM, 251),
    'M_MLight2'  : Button(TLPM, 252),
    'M_MLight3'  : Button(TLPM, 253),
    'M_MLight4'  : Button(TLPM, 254),
    'M_MBUp'     : Button(TLPM, 255),
    'M_MBStop'   : Button(TLPM, 256),
    'M_MBDown'   : Button(TLPM, 257),
    ## Page Room M - VoIP Full
    ## VoIP Dial
    'Call'      : Button(TLPM, 276),
    'Hangup'    : Button(TLPM, 277),
    ## VoIP Numbers
    'Dial0'     : Button(TLPM, 260),
    'Dial1'     : Button(TLPM, 261),
    'Dial2'     : Button(TLPM, 262),
    'Dial3'     : Button(TLPM, 263),
    'Dial4'     : Button(TLPM, 264),
    'Dial5'     : Button(TLPM, 265),
    'Dial6'     : Button(TLPM, 266),
    'Dial7'     : Button(TLPM, 267),
    'Dial8'     : Button(TLPM, 268),
    'Dial9'     : Button(TLPM, 269),
    'DialA'     : Button(TLPM, 270),
    'DialG'     : Button(TLPM, 271),
    'Delete'    : Button(TLPM, 275, repeatTime=0.1),
    ## VoIP Options
    'Redial'    : Button(TLPM, 272),
    'DTMF'      : Button(TLPM, 273),
    'Hold'      : Button(TLPM, 274),
    ## Page Room M - Video Executive
    'M_EProjA'  : Button(TLPM, 281),
    'M_EProjB'  : Button(TLPM, 282),
    'M_EProjD'  : Button(TLPM, 283),
    ## Page Room M - Lights Executive
    'M_ELightA' : Button(TLPM, 291),
    'M_ELightB' : Button(TLPM, 292),
    ## Page Room M - PowerOff
    'M_ABCPwrAll' : Button(TLPM, 301, holdTime=3),

    ## PANEL A ----------------------------------------
    ## Page Index
    'A_Index'   : Button(TLP1, 1),
    ## Page Room A - PIN
    'A_Pin0'    : Button(TLP1, 1000),
    'A_Pin1'    : Button(TLP1, 1001),
    'A_Pin2'    : Button(TLP1, 1002),
    'A_Pin3'    : Button(TLP1, 1003),
    'A_Pin4'    : Button(TLP1, 1004),
    'A_Pin5'    : Button(TLP1, 1005),
    'A_Pin6'    : Button(TLP1, 1006),
    'A_Pin7'    : Button(TLP1, 1007),
    'A_Pin8'    : Button(TLP1, 1008),
    'A_Pin9'    : Button(TLP1, 1009),
    'A_PinD'    : Button(TLP1, 1010, repeatTime=0.1),
    'A_PinX'    : Button(TLP1, 1011),
    ## Page Room A - Main
    'A_Video'   : Button(TLP1, 11),
    'A_Audio'   : Button(TLP1, 12),
    'A_Lights'  : Button(TLP1, 13),
    'A_PwrOff'  : Button(TLP1, 14),
    'A_RoomA'   : Button(TLP1, 22),
    'A_RoomB'   : Button(TLP1, 23),
    'A_RoomC'   : Button(TLP1, 24),
    'A_Devio'   : Button(TLP1, 25),
    'A_SW4HD'   : Button(TLP1, 26),
    ## Page Room A - Video
    'A_VHDMI'   : Button(TLP1, 31),
    'A_VShare'  : Button(TLP1, 32),
    'A_Signal1' : Button(TLP1, 33),
    'A_Signal2' : Button(TLP1, 34),
    'A_VPwrOn'  : Button(TLP1, 35),
    'A_VPwrOff' : Button(TLP1, 36),
    'A_Up'      : Button(TLP1, 37),
    'A_Stop'    : Button(TLP1, 38),
    'A_Down'    : Button(TLP1, 39),
    ## Page Room A - Audio
    'A_VolLess' : Button(TLP1, 41, repeatTime=0.1),
    'A_VolPlus' : Button(TLP1, 42, repeatTime=0.1),
    'A_Mute'    : Button(TLP1, 43),
    ## Page Room A - Lights & Blinds
    'A_Light1'  : Button(TLP1, 51),
    'A_Light2'  : Button(TLP1, 52),
    'A_Light3'  : Button(TLP1, 53),
    'A_Light4'  : Button(TLP1, 54),
    'A_BUp'     : Button(TLP1, 55),
    'A_BStop'   : Button(TLP1, 56),
    'A_BDown'   : Button(TLP1, 57),
    ## Page Room A - PowerOff
    'A_PwrAll'  : Button(TLP1, 61, holdTime=3),
    ## Page Room A - Main Full
    'A_FVideo'  : Button(TLP1, 111),
    'A_FAudio'  : Button(TLP1, 112),
    'A_FLights' : Button(TLP1, 113),
    'A_VoIP'    : Button(TLP1, 114),
    'A_FPwrOff' : Button(TLP1, 115),
    'A_FRoomA'  : Button(TLP1, 122),
    'A_FRoomB'  : Button(TLP1, 123),
    'A_FRoomC'  : Button(TLP1, 124),
    'A_Somfy'   : Button(TLP1, 125),
    'A_Lutron'  : Button(TLP1, 126),
    'A_Tesira'  : Button(TLP1, 127),
    'A_Matrix'  : Button(TLP1, 128),
    'A_Devio1'  : Button(TLP1, 129),
    'A_Devio2'  : Button(TLP1, 130),
    'A_Devio3'  : Button(TLP1, 131),
    'A_SW4HD1'  : Button(TLP1, 132),
    'A_SW4HD2'  : Button(TLP1, 133),
    'A_SW4HD3'  : Button(TLP1, 134),
    ## Page Room A - Video Full
    'A_ProjA'   : Button(TLP1, 141),
    'A_ProjB'   : Button(TLP1, 142),
    'A_ProjC'   : Button(TLP1, 143),
    'A_ProjD'   : Button(TLP1, 144),
    'A_ProjM'   : Button(TLP1, 145),
    ## Page Room A - Video Proj A Full
    'A_P1HDMI'    : Button(TLP1, 151),
    'A_P1Share'   : Button(TLP1, 152),
    'A_P1Signal1' : Button(TLP1, 153),
    'A_P1Signal2' : Button(TLP1, 154),
    'A_P1PwrOn'   : Button(TLP1, 155),
    'A_P1PwrOff'  : Button(TLP1, 156),
    'A_P1Up'      : Button(TLP1, 157),
    'A_P1Stop'    : Button(TLP1, 158),
    'A_P1Down'    : Button(TLP1, 159),
    'A_P1Back'    : Button(TLP1, 160),
    ## Page Room A - Video Proj B Full
    'A_P2HDMI'    : Button(TLP1, 161),
    'A_P2Share'   : Button(TLP1, 162),
    'A_P2Signal1' : Button(TLP1, 163),
    'A_P2Signal2' : Button(TLP1, 164),
    'A_P2PwrOn'   : Button(TLP1, 165),
    'A_P2PwrOff'  : Button(TLP1, 166),
    'A_P2Up'      : Button(TLP1, 167),
    'A_P2Stop'    : Button(TLP1, 168),
    'A_P2Down'    : Button(TLP1, 169),
    'A_P2Back'    : Button(TLP1, 170),
    ## Page Room A - Video Proj C Full
    'A_P3HDMI'    : Button(TLP1, 171),
    'A_P3Share'   : Button(TLP1, 172),
    'A_P3Signal1' : Button(TLP1, 173),
    'A_P3Signal2' : Button(TLP1, 174),
    'A_P3PwrOn'   : Button(TLP1, 175),
    'A_P3PwrOff'  : Button(TLP1, 176),
    'A_P3Up'      : Button(TLP1, 177),
    'A_P3Stop'    : Button(TLP1, 178),
    'A_P3Down'    : Button(TLP1, 179),
    'A_P3Back'    : Button(TLP1, 180),
    ## Page Room A - Video Proj D Full
    'A_P4HDMI'    : Button(TLP1, 181),
    'A_P4Share'   : Button(TLP1, 182),
    'A_P4Signal1' : Button(TLP1, 183),
    'A_P4Signal2' : Button(TLP1, 184),
    'A_P4PwrOn'   : Button(TLP1, 185),
    'A_P4PwrOff'  : Button(TLP1, 186),
    'A_P4Up'      : Button(TLP1, 187),
    'A_P4Stop'    : Button(TLP1, 188),
    'A_P4Down'    : Button(TLP1, 189),
    'A_P4Back'    : Button(TLP1, 190),
    ## Page Room A - Video Proj All Full
    'A_PMHDMI'    : Button(TLP1, 191),
    'A_PMSignal1' : Button(TLP1, 192),
    'A_PMShare'   : Button(TLP1, 193),
    'A_PMSignal2' : Button(TLP1, 194),
    'A_PMUp'      : Button(TLP1, 195),
    'A_PMStop'    : Button(TLP1, 196),
    'A_PMDown'    : Button(TLP1, 197),
    'A_PMBack'    : Button(TLP1, 198),
    ## Page Room A - Audio Full
    'A_.HDMI'    : Button(TLP1, 201),
    'A_.Signal1'  : Button(TLP1, 202),
    'A_.Share'    : Button(TLP1, 203),
    'A_.Signal2'  : Button(TLP1, 204),
    'A_.VolLess'  : Button(TLP1, 205, repeatTime=0.1),
    'A_.VolPlus'  : Button(TLP1, 206, repeatTime=0.1),
    'A_.MuteSpk'  : Button(TLP1, 208),
    'A_.MuteMiM'  : Button(TLP1, 209),
    'A_.MuteMiT'  : Button(TLP1, 210),
    ## Page Room A - Lights Full
    'A_LightA'   : Button(TLP1, 211),
    'A_LightB'   : Button(TLP1, 212),
    'A_LightC'   : Button(TLP1, 213),
    'A_LightM'   : Button(TLP1, 214),
    ## Page Room A - Lights & Blinds Full
    'A_ALight1'  : Button(TLP1, 221),
    'A_ALight2'  : Button(TLP1, 222),
    'A_ALight3'  : Button(TLP1, 223),
    'A_ALight4'  : Button(TLP1, 224),
    'A_ABUp'     : Button(TLP1, 225),
    'A_ABStop'   : Button(TLP1, 226),
    'A_ABDown'   : Button(TLP1, 227),
    ## Page Room B - Lights & Blinds Full
    'A_BLight1'  : Button(TLP1, 231),
    'A_BLight2'  : Button(TLP1, 232),
    'A_BLight3'  : Button(TLP1, 233),
    'A_BLight4'  : Button(TLP1, 234),
    'A_BBUp'     : Button(TLP1, 235),
    'A_BBStop'   : Button(TLP1, 236),
    'A_BBDown'   : Button(TLP1, 237),
    ## Page Room C - Lights & Blinds Full
    'A_CLight1'  : Button(TLP1, 241),
    'A_CLight2'  : Button(TLP1, 242),
    'A_CLight3'  : Button(TLP1, 243),
    'A_CLight4'  : Button(TLP1, 244),
    'A_CBUp'     : Button(TLP1, 245),
    'A_CBStop'   : Button(TLP1, 246),
    'A_CBDown'   : Button(TLP1, 247),
    ## Page Room M - Lights & Blinds Full
    'A_MLight1'  : Button(TLP1, 251),
    'A_MLight2'  : Button(TLP1, 252),
    'A_MLight3'  : Button(TLP1, 253),
    'A_MLight4'  : Button(TLP1, 254),
    'A_MBUp'     : Button(TLP1, 255),
    'A_MBStop'   : Button(TLP1, 256),
    'A_MBDown'   : Button(TLP1, 257),
    ## Page Room A - VoIP Full
    ## VoIP Dial
    'Call'      : Button(TLP1, 276),
    'Hangup'    : Button(TLP1, 277),
    ## VoIP Numbers
    'Dial0'     : Button(TLP1, 260),
    'Dial1'     : Button(TLP1, 261),
    'Dial2'     : Button(TLP1, 262),
    'Dial3'     : Button(TLP1, 263),
    'Dial4'     : Button(TLP1, 264),
    'Dial5'     : Button(TLP1, 265),
    'Dial6'     : Button(TLP1, 266),
    'Dial7'     : Button(TLP1, 267),
    'Dial8'     : Button(TLP1, 268),
    'Dial9'     : Button(TLP1, 269),
    'DialA'     : Button(TLP1, 270),
    'DialG'     : Button(TLP1, 271),
    'Delete'    : Button(TLP1, 275, repeatTime=0.1),
    ## VoIP Options
    'Redial'    : Button(TLP1, 272),
    'DTMF'      : Button(TLP1, 273),
    'Hold'      : Button(TLP1, 274),
    ## Page Room A - Video Executive
    'A_EProjA'  : Button(TLP1, 281),
    'A_EProjB'  : Button(TLP1, 282),
    'A_EProjD'  : Button(TLP1, 283),
    ## Page Room A - Lights Executive
    'A_ELightA' : Button(TLP1, 291),
    'A_ELightB' : Button(TLP1, 292),
    ## Page Room A - PowerOff
    'A_ABCPwrAll' : Button(TLP1, 301, holdTime=3),

    ## PANEL B ----------------------------------------
    ## Page Index
    'B_Index'   : Button(TLP2, 1),
    ## Page Room B - PIN
    'B_Pin0'    : Button(TLP2, 1000),
    'B_Pin1'    : Button(TLP2, 1001),
    'B_Pin2'    : Button(TLP2, 1002),
    'B_Pin3'    : Button(TLP2, 1003),
    'B_Pin4'    : Button(TLP2, 1004),
    'B_Pin5'    : Button(TLP2, 1005),
    'B_Pin6'    : Button(TLP2, 1006),
    'B_Pin7'    : Button(TLP2, 1007),
    'B_Pin8'    : Button(TLP2, 1008),
    'B_Pin9'    : Button(TLP2, 1009),
    'B_PinD'    : Button(TLP2, 1010, repeatTime=0.1),
    'B_PinX'    : Button(TLP2, 1011),
    ## Page Room B - Main
    'B_Video'   : Button(TLP2, 11),
    'B_Audio'   : Button(TLP2, 12),
    'B_Lights'  : Button(TLP2, 13),
    'B_PwrOff'  : Button(TLP2, 14),
    'B_RoomA'   : Button(TLP2, 22),
    'B_RoomB'   : Button(TLP2, 23),
    'B_RoomC'   : Button(TLP2, 24),
    'B_Devio'   : Button(TLP2, 25),
    'B_SW4HD'   : Button(TLP2, 26),
    ## Page Room B - Video
    'B_VHDMI'   : Button(TLP2, 31),
    'B_VShare'  : Button(TLP2, 32),
    'B_Signal1' : Button(TLP2, 33),
    'B_Signal2' : Button(TLP2, 34),
    'B_VPwrOn'  : Button(TLP2, 35),
    'B_VPwrOff' : Button(TLP2, 36),
    'B_Up'      : Button(TLP2, 37),
    'B_Stop'    : Button(TLP2, 38),
    'B_Down'    : Button(TLP2, 39),
    ## Page Room B - Audio
    'B_VolLess' : Button(TLP2, 41, repeatTime=0.1),
    'B_VolPlus' : Button(TLP2, 42, repeatTime=0.1),
    'B_Mute'    : Button(TLP2, 43),
    ## Page Room B - Lights & Blinds
    'B_Light1'  : Button(TLP2, 51),
    'B_Light2'  : Button(TLP2, 52),
    'B_Light3'  : Button(TLP2, 53),
    'B_Light4'  : Button(TLP2, 54),
    'B_BUp'     : Button(TLP2, 55),
    'B_BStop'   : Button(TLP2, 56),
    'B_BDown'   : Button(TLP2, 57),
    ## Page Room B - PowerOff
    'B_PwrAll'  : Button(TLP2, 61, holdTime=3),
    ## Page Room B - Main Full
    'B_FVideo'   : Button(TLP2, 111),
    'B_FAudio'   : Button(TLP2, 112),
    'B_FLights'  : Button(TLP2, 113),
    'B_VoIP'    : Button(TLP2, 114),
    'B_FPwrOff'  : Button(TLP2, 115),
    'B_FRoomA'   : Button(TLP2, 122),
    'B_FRoomB'   : Button(TLP2, 123),
    'B_FRoomC'   : Button(TLP2, 124),
    'B_Somfy'   : Button(TLP2, 125),
    'B_Lutron'  : Button(TLP2, 126),
    'B_Tesira'  : Button(TLP2, 127),
    'B_Matrix'  : Button(TLP2, 128),
    'B_Devio1'  : Button(TLP2, 129),
    'B_Devio2'  : Button(TLP2, 130),
    'B_Devio3'  : Button(TLP2, 131),
    'B_SW4HD1'  : Button(TLP2, 132),
    'B_SW4HD2'  : Button(TLP2, 133),
    'B_SW4HD3'  : Button(TLP2, 134),
    ## Page Room B - Video Full
    'B_ProjA'   : Button(TLP2, 141),
    'B_ProjB'   : Button(TLP2, 142),
    'B_ProjC'   : Button(TLP2, 143),
    'B_ProjD'   : Button(TLP2, 144),
    'B_ProjM'   : Button(TLP2, 145),
    ## Page Room B - Video Proj A Full
    'B_P1HDMI'    : Button(TLP2, 151),
    'B_P1Share'   : Button(TLP2, 152),
    'B_P1Signal1' : Button(TLP2, 153),
    'B_P1Signal2' : Button(TLP2, 154),
    'B_P1PwrOn'   : Button(TLP2, 155),
    'B_P1PwrOff'  : Button(TLP2, 156),
    'B_P1Up'      : Button(TLP2, 157),
    'B_P1Stop'    : Button(TLP2, 158),
    'B_P1Down'    : Button(TLP2, 159),
    'B_P1Back'    : Button(TLP2, 160),
    ## Page Room B - Video Proj B Full
    'B_P2HDMI'    : Button(TLP2, 161),
    'B_P2Share'   : Button(TLP2, 162),
    'B_P2Signal1' : Button(TLP2, 163),
    'B_P2Signal2' : Button(TLP2, 164),
    'B_P2PwrOn'   : Button(TLP2, 165),
    'B_P2PwrOff'  : Button(TLP2, 166),
    'B_P2Up'      : Button(TLP2, 167),
    'B_P2Stop'    : Button(TLP2, 168),
    'B_P2Down'    : Button(TLP2, 169),
    'B_P2Back'    : Button(TLP2, 170),
    ## Page Room B - Video Proj C Full
    'B_P3HDMI'    : Button(TLP2, 171),
    'B_P3Share'   : Button(TLP2, 172),
    'B_P3Signal1' : Button(TLP2, 173),
    'B_P3Signal2' : Button(TLP2, 174),
    'B_P3PwrOn'   : Button(TLP2, 175),
    'B_P3PwrOff'  : Button(TLP2, 176),
    'B_P3Up'      : Button(TLP2, 177),
    'B_P3Stop'    : Button(TLP2, 178),
    'B_P3Down'    : Button(TLP2, 179),
    'B_P3Back'    : Button(TLP2, 180),
    ## Page Room B - Video Proj D Full
    'B_P4HDMI'    : Button(TLP2, 181),
    'B_P4Share'   : Button(TLP2, 182),
    'B_P4Signal1' : Button(TLP2, 183),
    'B_P4Signal2' : Button(TLP2, 184),
    'B_P4PwrOn'   : Button(TLP2, 185),
    'B_P4PwrOff'  : Button(TLP2, 186),
    'B_P4Up'      : Button(TLP2, 187),
    'B_P4Stop'    : Button(TLP2, 188),
    'B_P4Down'    : Button(TLP2, 189),
    'B_P4Back'    : Button(TLP2, 190),
    ## Page Room B - Video Proj All Full
    'B_PMHDMI'    : Button(TLP2, 191),
    'B_PMSignal1' : Button(TLP2, 192),
    'B_PMShare'   : Button(TLP2, 193),
    'B_PMSignal2' : Button(TLP2, 194),
    'B_PMUp'      : Button(TLP2, 195),
    'B_PMStop'    : Button(TLP2, 196),
    'B_PMDown'    : Button(TLP2, 197),
    'B_PMBack'    : Button(TLP2, 198),
    ## Page Room B - Audio Full
    'B_.HDMI'     : Button(TLP2, 201),
    'B_.Signal1'  : Button(TLP2, 202),
    'B_.Share'    : Button(TLP2, 203),
    'B_.Signal2'  : Button(TLP2, 204),
    'B_.VolLess'  : Button(TLP2, 205, repeatTime=0.1),
    'B_.VolPlus'  : Button(TLP2, 206, repeatTime=0.1),
    'B_.MuteSpk'  : Button(TLP2, 208),
    'B_.MuteMiM'  : Button(TLP2, 209),
    'B_.MuteMiT'  : Button(TLP2, 210),
    ## Page Room B - Lights Full
    'B_LightA'    : Button(TLP2, 211),
    'B_LightB'    : Button(TLP2, 212),
    'B_LightC'    : Button(TLP2, 213),
    'B_LightM'    : Button(TLP2, 214),
    ## Page Room B - Lights & Blinds Full
    'B_ALight1'  : Button(TLP2, 221),
    'B_ALight2'  : Button(TLP2, 222),
    'B_ALight3'  : Button(TLP2, 223),
    'B_ALight4'  : Button(TLP2, 224),
    'B_ABUp'     : Button(TLP2, 225),
    'B_ABStop'   : Button(TLP2, 226),
    'B_ABDown'   : Button(TLP2, 227),
    ## Page Room B - Lights & Blinds Full
    'B_BLight1'  : Button(TLP2, 231),
    'B_BLight2'  : Button(TLP2, 232),
    'B_BLight3'  : Button(TLP2, 233),
    'B_BLight4'  : Button(TLP2, 234),
    'B_BBUp'     : Button(TLP2, 235),
    'B_BBStop'   : Button(TLP2, 236),
    'B_BBDown'   : Button(TLP2, 237),
    ## Page Room C - Lights & Blinds Full
    'B_CLight1'  : Button(TLP2, 241),
    'B_CLight2'  : Button(TLP2, 242),
    'B_CLight3'  : Button(TLP2, 243),
    'B_CLight4'  : Button(TLP2, 244),
    'B_CBUp'     : Button(TLP2, 245),
    'B_CBStop'   : Button(TLP2, 246),
    'B_CBDown'   : Button(TLP2, 247),
    ## Page Room M - Lights & Blinds Full
    'B_MLight1'  : Button(TLP2, 251),
    'B_MLight2'  : Button(TLP2, 252),
    'B_MLight3'  : Button(TLP2, 253),
    'B_MLight4'  : Button(TLP2, 254),
    'B_MBUp'     : Button(TLP2, 255),
    'B_MBStop'   : Button(TLP2, 256),
    'B_MBDown'   : Button(TLP2, 257),
    ## Page Room B - VoIP Full
    ## VoIP Dial
    'Call'      : Button(TLP2, 276),
    'Hangup'    : Button(TLP2, 277),
    ## VoIP Numbers
    'Dial0'     : Button(TLP2, 260),
    'Dial1'     : Button(TLP2, 261),
    'Dial2'     : Button(TLP2, 262),
    'Dial3'     : Button(TLP2, 263),
    'Dial4'     : Button(TLP2, 264),
    'Dial5'     : Button(TLP2, 265),
    'Dial6'     : Button(TLP2, 266),
    'Dial7'     : Button(TLP2, 267),
    'Dial8'     : Button(TLP2, 268),
    'Dial9'     : Button(TLP2, 269),
    'DialA'     : Button(TLP2, 270),
    'DialG'     : Button(TLP2, 271),
    'Delete'    : Button(TLP2, 275, repeatTime=0.1),
    ## VoIP Options
    'Redial'    : Button(TLP2, 272),
    'DTMF'      : Button(TLP2, 273),
    'Hold'      : Button(TLP2, 274),
    ## Page Room B - Video Executive
    'B_EProjA'  : Button(TLP2, 281),
    'B_EProjB'  : Button(TLP2, 282),
    'B_EProjD'  : Button(TLP2, 283),
    ## Page Room B - Lights Executive
    'B_ELightA' : Button(TLP2, 291),
    'B_ELightB' : Button(TLP2, 292),
    ## Page Room B - PowerOff
    'B_ABCPwrAll' : Button(TLP2, 301, holdTime=3),


    ## PANEL c ----------------------------------------
    ## Page Index
    'C_Index'   : Button(TLP3, 1),
    ## Page Room C - PIN
    'C_Pin0'    : Button(TLP3, 1000),
    'C_Pin1'    : Button(TLP3, 1001),
    'C_Pin2'    : Button(TLP3, 1002),
    'C_Pin3'    : Button(TLP3, 1003),
    'C_Pin4'    : Button(TLP3, 1004),
    'C_Pin5'    : Button(TLP3, 1005),
    'C_Pin6'    : Button(TLP3, 1006),
    'C_Pin7'    : Button(TLP3, 1007),
    'C_Pin8'    : Button(TLP3, 1008),
    'C_Pin9'    : Button(TLP3, 1009),
    'C_PinD'    : Button(TLP3, 1010, repeatTime=0.1),
    'C_PinX'    : Button(TLP3, 1011),
    ## Page Room C - Main
    'C_Video'   : Button(TLP3, 11),
    'C_Audio'   : Button(TLP3, 12),
    'C_Lights'  : Button(TLP3, 13),
    'C_PwrOff'  : Button(TLP3, 14),
    'C_RoomA'   : Button(TLP3, 22),
    'C_RoomB'   : Button(TLP3, 23),
    'C_RoomC'   : Button(TLP3, 24),
    'C_Devio'   : Button(TLP3, 25),
    'C_SW4HD'   : Button(TLP3, 26),
    ## Page Room C - Video
    'C_VHDMI'   : Button(TLP3, 31),
    'C_VShare'  : Button(TLP3, 32),
    'C_Signal1' : Button(TLP3, 33),
    'C_Signal2' : Button(TLP3, 34),
    'C_VPwrOn'  : Button(TLP3, 35),
    'C_VPwrOff' : Button(TLP3, 36),
    'C_Up'      : Button(TLP3, 37),
    'C_Stop'    : Button(TLP3, 38),
    'C_Down'    : Button(TLP3, 39),
    ## Page Room C - Audio
    'C_VolLess' : Button(TLP3, 41, repeatTime=0.1),
    'C_VolPlus' : Button(TLP3, 42, repeatTime=0.1),
    'C_Mute'    : Button(TLP3, 43),
    ## Page Room C - Lights & Blinds
    'C_Light1'  : Button(TLP3, 51),
    'C_Light2'  : Button(TLP3, 52),
    'C_Light3'  : Button(TLP3, 53),
    'C_Light4'  : Button(TLP3, 54),
    'C_BUp'     : Button(TLP3, 55),
    'C_BStop'   : Button(TLP3, 56),
    'C_BDown'   : Button(TLP3, 57),
    ## Page Room C - PowerOff
    'C_PwrAll'  : Button(TLP3, 61, holdTime=3),
    ## Page Room C - Main Full
    'C_FVideo'   : Button(TLP3, 111),
    'C_FAudio'   : Button(TLP3, 112),
    'C_FLights'  : Button(TLP3, 113),
    'C_VoIP'    : Button(TLP3, 114),
    'C_FPwrOff'  : Button(TLP3, 115),
    'C_FRoomA'   : Button(TLP3, 122),
    'C_FRoomB'   : Button(TLP3, 123),
    'C_FRoomC'   : Button(TLP3, 124),
    'C_Somfy'   : Button(TLP3, 125),
    'C_Lutron'  : Button(TLP3, 126),
    'C_Tesira'  : Button(TLP3, 127),
    'C_Matrix'  : Button(TLP3, 128),
    'C_Devio1'  : Button(TLP3, 129),
    'C_Devio2'  : Button(TLP3, 130),
    'C_Devio3'  : Button(TLP3, 131),
    'C_SW4HD1'  : Button(TLP3, 132),
    'C_SW4HD2'  : Button(TLP3, 133),
    'C_SW4HD3'  : Button(TLP3, 134),
    ## Page Room C - Video Full
    'C_ProjA'   : Button(TLP3, 141),
    'C_ProjB'   : Button(TLP3, 142),
    'C_ProjC'   : Button(TLP3, 143),
    'C_ProjD'   : Button(TLP3, 144),
    'C_ProjM'   : Button(TLP3, 145),
    ## Page Room C - Video Proj A Full
    'C_P1HDMI'    : Button(TLP3, 151),
    'C_P1Share'   : Button(TLP3, 152),
    'C_P1Signal1' : Button(TLP3, 153),
    'C_P1Signal2' : Button(TLP3, 154),
    'C_P1PwrOn'   : Button(TLP3, 155),
    'C_P1PwrOff'  : Button(TLP3, 156),
    'C_P1Up'      : Button(TLP3, 157),
    'C_P1Stop'    : Button(TLP3, 158),
    'C_P1Down'    : Button(TLP3, 159),
    'C_P1Back'    : Button(TLP3, 160),
    ## Page Room C - Video Proj B Full
    'C_P2HDMI'    : Button(TLP3, 161),
    'C_P2Share'   : Button(TLP3, 162),
    'C_P2Signal1' : Button(TLP3, 163),
    'C_P2Signal2' : Button(TLP3, 164),
    'C_P2PwrOn'   : Button(TLP3, 165),
    'C_P2PwrOff'  : Button(TLP3, 166),
    'C_P2Up'      : Button(TLP3, 167),
    'C_P2Stop'    : Button(TLP3, 168),
    'C_P2Down'    : Button(TLP3, 169),
    'C_P2Back'    : Button(TLP3, 170),
    ## Page Room C - Video Proj C Full
    'C_P3HDMI'    : Button(TLP3, 171),
    'C_P3Share'   : Button(TLP3, 172),
    'C_P3Signal1' : Button(TLP3, 173),
    'C_P3Signal2' : Button(TLP3, 174),
    'C_P3PwrOn'   : Button(TLP3, 175),
    'C_P3PwrOff'  : Button(TLP3, 176),
    'C_P3Up'      : Button(TLP3, 177),
    'C_P3Stop'    : Button(TLP3, 178),
    'C_P3Down'    : Button(TLP3, 179),
    'C_P3Back'    : Button(TLP3, 180),
    ## Page Room C - Video Proj D Full
    'C_P4HDMI'    : Button(TLP3, 181),
    'C_P4Share'   : Button(TLP3, 182),
    'C_P4Signal1' : Button(TLP3, 183),
    'C_P4Signal2' : Button(TLP3, 184),
    'C_P4PwrOn'   : Button(TLP3, 185),
    'C_P4PwrOff'  : Button(TLP3, 186),
    'C_P4Up'      : Button(TLP3, 187),
    'C_P4Stop'    : Button(TLP3, 188),
    'C_P4Down'    : Button(TLP3, 189),
    'C_P4Back'    : Button(TLP3, 190),
    ## Page Room C - Video Proj All Full
    'C_PMHDMI'    : Button(TLP3, 191),
    'C_PMSignal1' : Button(TLP3, 192),
    'C_PMShare'   : Button(TLP3, 193),
    'C_PMSignal2' : Button(TLP3, 194),
    'C_PMUp'      : Button(TLP3, 195),
    'C_PMStop'    : Button(TLP3, 196),
    'C_PMDown'    : Button(TLP3, 197),
    'C_PMBack'    : Button(TLP3, 198),
    ## Page Room C - Audio Full
    'C_.HDMI'     : Button(TLP3, 201),
    'C_.Signal1'  : Button(TLP3, 202),
    'C_.Share'    : Button(TLP3, 203),
    'C_.Signal2'  : Button(TLP3, 204),
    'C_.VolLess'  : Button(TLP3, 205, repeatTime=0.1),
    'C_.VolPlus'  : Button(TLP3, 206, repeatTime=0.1),
    'C_.MuteSpk'  : Button(TLP3, 208),
    'C_.MuteMiM'  : Button(TLP3, 209),
    'C_.MuteMiT'  : Button(TLP3, 210),
    ## Page Room C - Lights Full
    'C_LightA'   : Button(TLP3, 211),
    'C_LightB'   : Button(TLP3, 212),
    'C_LightC'   : Button(TLP3, 213),
    'C_LightM'   : Button(TLP3, 214),
    ## Page Room C - Lights & Blinds Full
    'C_ALight1'  : Button(TLP3, 221),
    'C_ALight2'  : Button(TLP3, 222),
    'C_ALight3'  : Button(TLP3, 223),
    'C_ALight4'  : Button(TLP3, 224),
    'C_ABUp'     : Button(TLP3, 225),
    'C_ABStop'   : Button(TLP3, 226),
    'C_ABDown'   : Button(TLP3, 227),
    ## Page Room B - Lights & Blinds Full
    'C_BLight1'  : Button(TLP3, 231),
    'C_BLight2'  : Button(TLP3, 232),
    'C_BLight3'  : Button(TLP3, 233),
    'C_BLight4'  : Button(TLP3, 234),
    'C_BBUp'     : Button(TLP3, 235),
    'C_BBStop'   : Button(TLP3, 236),
    'C_BBDown'   : Button(TLP3, 237),
    ## Page Room C - Lights & Blinds Full
    'C_CLight1'  : Button(TLP3, 241),
    'C_CLight2'  : Button(TLP3, 242),
    'C_CLight3'  : Button(TLP3, 243),
    'C_CLight4'  : Button(TLP3, 244),
    'C_CBUp'     : Button(TLP3, 245),
    'C_CBStop'   : Button(TLP3, 246),
    'C_CBDown'   : Button(TLP3, 247),
    ## Page Room M - Lights & Blinds Full
    'C_MLight1'  : Button(TLP3, 251),
    'C_MLight2'  : Button(TLP3, 252),
    'C_MLight3'  : Button(TLP3, 253),
    'C_MLight4'  : Button(TLP3, 254),
    'C_MBUp'     : Button(TLP3, 255),
    'C_MBStop'   : Button(TLP3, 256),
    'C_MBDown'   : Button(TLP3, 257),
    ## Page Room C - VoIP Full
    ## VoIP Dial
    'Call'      : Button(TLP3, 276),
    'Hangup'    : Button(TLP3, 277),
    ## VoIP Numbers
    'Dial0'     : Button(TLP3, 260),
    'Dial1'     : Button(TLP3, 261),
    'Dial2'     : Button(TLP3, 262),
    'Dial3'     : Button(TLP3, 263),
    'Dial4'     : Button(TLP3, 264),
    'Dial5'     : Button(TLP3, 265),
    'Dial6'     : Button(TLP3, 266),
    'Dial7'     : Button(TLP3, 267),
    'Dial8'     : Button(TLP3, 268),
    'Dial9'     : Button(TLP3, 269),
    'DialA'     : Button(TLP3, 270),
    'DialG'     : Button(TLP3, 271),
    'Delete'    : Button(TLP3, 275, repeatTime=0.1),
    ## VoIP Options
    'Redial'    : Button(TLP3, 272),
    'DTMF'      : Button(TLP3, 273),
    'Hold'      : Button(TLP3, 274),
    ## Page Room C - Video Executive
    'C_EProjA'  : Button(TLP3, 281),
    'C_EProjB'  : Button(TLP3, 282),
    'C_EProjD'  : Button(TLP3, 283),
    ## Page Room C - Lights Executive
    'C_ELightA' : Button(TLP3, 291),
    'C_ELightB' : Button(TLP3, 292),
    ## Page Room C - PowerOff
    'C_ABCPwrAll' : Button(TLP3, 301, holdTime=3),
}

# UI Page Buttons
BTNPAGE = {
    'Index' : [BTN['A_Index'], BTN['B_Index'], BTN['C_Index'], BTN['M_Index']],
    'Room'  : [BTN['M_Mode1'], BTN['M_Mode2'], BTN['M_Mode3']],

    'PIN'   : [BTN['M_Pin0'], BTN['M_Pin1'], BTN['M_Pin2'], BTN['M_Pin3'], BTN['M_Pin4'], BTN['M_Pin5'],
               BTN['M_Pin6'], BTN['M_Pin7'], BTN['M_Pin8'], BTN['M_Pin9'], BTN['M_PinD'], BTN['M_PinX'],
               BTN['A_Pin0'], BTN['A_Pin1'], BTN['A_Pin2'], BTN['A_Pin3'], BTN['A_Pin4'], BTN['A_Pin5'],
               BTN['A_Pin6'], BTN['A_Pin7'], BTN['A_Pin8'], BTN['A_Pin9'], BTN['A_PinD'], BTN['A_PinX'],
               BTN['B_Pin0'], BTN['B_Pin1'], BTN['B_Pin2'], BTN['B_Pin3'], BTN['B_Pin4'], BTN['B_Pin5'],
               BTN['B_Pin6'], BTN['B_Pin7'], BTN['B_Pin8'], BTN['B_Pin9'], BTN['B_PinD'], BTN['B_PinX'],
               BTN['C_Pin0'], BTN['C_Pin1'], BTN['C_Pin2'], BTN['C_Pin3'], BTN['C_Pin4'], BTN['C_Pin5'],
               BTN['C_Pin6'], BTN['C_Pin7'], BTN['C_Pin8'], BTN['C_Pin9'], BTN['C_PinD'], BTN['C_PinX']],
    
    'Main'  : [BTN['A_Video'], BTN['A_Audio'], BTN['A_Lights'], BTN['A_PwrOff'],
               BTN['B_Video'], BTN['B_Audio'], BTN['B_Lights'], BTN['B_PwrOff'],
               BTN['C_Video'], BTN['C_Audio'], BTN['C_Lights'], BTN['C_PwrOff'], BTN['M_Config']],

    'Main_F': [BTN['M_FVideo'], BTN['A_FVideo'], BTN['B_FVideo'], BTN['C_FVideo'],
               BTN['M_FAudio'], BTN['A_FAudio'], BTN['B_FAudio'], BTN['C_FAudio'],
               BTN['M_FLights'], BTN['A_FLights'], BTN['B_FLights'], BTN['C_FLights'], 
               BTN['M_VoIP'], BTN['A_VoIP'], BTN['B_VoIP'], BTN['C_VoIP'],
               BTN['M_FPwrOff'],  BTN['A_FPwrOff'],  BTN['B_FPwrOff'],  BTN['C_FPwrOff']],

    'Video' : [BTN['A_VHDMI'], BTN['A_VShare'], BTN['A_Signal1'], BTN['A_Signal2'], BTN['A_VPwrOn'], BTN['A_VPwrOff'], BTN['A_Up'], BTN['A_Stop'], BTN['A_Down'],
               BTN['B_VHDMI'], BTN['B_VShare'], BTN['B_Signal1'], BTN['B_Signal2'], BTN['B_VPwrOn'], BTN['B_VPwrOff'], BTN['B_Up'], BTN['B_Stop'], BTN['B_Down'],
               BTN['C_VHDMI'], BTN['C_VShare'], BTN['C_Signal1'], BTN['C_Signal2'], BTN['C_VPwrOn'], BTN['C_VPwrOff'], BTN['C_Up'], BTN['C_Stop'], BTN['C_Down']],

    ## Video Executive Mode
    'VideoE': [BTN['A_EProjA'], BTN['A_EProjB'], BTN['A_EProjD'],
               BTN['B_EProjA'], BTN['B_EProjB'], BTN['B_EProjD'],
               BTN['C_EProjA'], BTN['C_EProjB'], BTN['C_EProjD'],
               BTN['M_EProjA'], BTN['M_EProjB'], BTN['M_EProjD']],

    ## Video Full Mode
    'VideoF': [BTN['A_ProjA'], BTN['A_ProjB'], BTN['A_ProjC'], BTN['A_ProjD'], BTN['A_ProjM'],
               BTN['B_ProjA'], BTN['B_ProjB'], BTN['B_ProjC'], BTN['B_ProjD'], BTN['B_ProjM'],
               BTN['C_ProjA'], BTN['C_ProjB'], BTN['C_ProjC'], BTN['C_ProjD'], BTN['C_ProjM'],
               BTN['M_ProjA'], BTN['M_ProjB'], BTN['M_ProjC'], BTN['M_ProjD'], BTN['M_ProjM']],

    ## Video Full A Mode
    'VideoFA': [BTN['A_P1HDMI'], BTN['A_P1Share'], BTN['A_P1PwrOn'], BTN['A_P1PwrOff'], BTN['A_P1Up'], BTN['A_P1Stop'], BTN['A_P1Down'], BTN['A_P1Back'],
                BTN['B_P1HDMI'], BTN['B_P1Share'], BTN['B_P1PwrOn'], BTN['B_P1PwrOff'], BTN['B_P1Up'], BTN['B_P1Stop'], BTN['B_P1Down'], BTN['B_P1Back'],
                BTN['C_P1HDMI'], BTN['C_P1Share'], BTN['C_P1PwrOn'], BTN['C_P1PwrOff'], BTN['C_P1Up'], BTN['C_P1Stop'], BTN['C_P1Down'], BTN['C_P1Back'],
                BTN['M_P1HDMI'], BTN['M_P1Share'], BTN['M_P1PwrOn'], BTN['M_P1PwrOff'], BTN['M_P1Up'], BTN['M_P1Stop'], BTN['M_P1Down'], BTN['M_P1Back']],

    ## Video Full B Mode
    'VideoFB': [BTN['A_P2HDMI'], BTN['A_P2Share'], BTN['A_P2PwrOn'], BTN['A_P2PwrOff'], BTN['A_P2Up'], BTN['A_P2Stop'], BTN['A_P2Down'], BTN['A_P2Back'],
                BTN['B_P2HDMI'], BTN['B_P2Share'], BTN['B_P2PwrOn'], BTN['B_P2PwrOff'], BTN['B_P2Up'], BTN['B_P2Stop'], BTN['B_P2Down'], BTN['B_P2Back'],
                BTN['C_P2HDMI'], BTN['C_P2Share'], BTN['C_P2PwrOn'], BTN['C_P2PwrOff'], BTN['C_P2Up'], BTN['C_P2Stop'], BTN['C_P2Down'], BTN['C_P2Back'],
                BTN['M_P2HDMI'], BTN['M_P2Share'], BTN['M_P2PwrOn'], BTN['M_P2PwrOff'], BTN['M_P2Up'], BTN['M_P2Stop'], BTN['M_P2Down'], BTN['M_P2Back']],

    ## Video Full C Mode
    'VideoFC': [BTN['A_P3HDMI'], BTN['A_P3Share'], BTN['A_P3PwrOn'], BTN['A_P3PwrOff'], BTN['A_P3Up'], BTN['A_P3Stop'], BTN['A_P3Down'], BTN['A_P3Back'],
                BTN['B_P3HDMI'], BTN['B_P3Share'], BTN['B_P3PwrOn'], BTN['B_P3PwrOff'], BTN['B_P3Up'], BTN['B_P3Stop'], BTN['B_P3Down'], BTN['B_P3Back'],
                BTN['C_P3HDMI'], BTN['C_P3Share'], BTN['C_P3PwrOn'], BTN['C_P3PwrOff'], BTN['C_P3Up'], BTN['C_P3Stop'], BTN['C_P3Down'], BTN['C_P3Back'],
                BTN['M_P3HDMI'], BTN['M_P3Share'], BTN['M_P3PwrOn'], BTN['M_P3PwrOff'], BTN['M_P3Up'], BTN['M_P3Stop'], BTN['M_P3Down'], BTN['M_P3Back']],

    ## Video Full D Mode
    'VideoFD': [BTN['A_P4HDMI'], BTN['A_P4Share'], BTN['A_P4PwrOn'], BTN['A_P4PwrOff'], BTN['A_P4Up'], BTN['A_P4Stop'], BTN['A_P4Down'], BTN['A_P4Back'],
                BTN['B_P4HDMI'], BTN['B_P4Share'], BTN['B_P4PwrOn'], BTN['B_P4PwrOff'], BTN['B_P4Up'], BTN['B_P4Stop'], BTN['B_P4Down'], BTN['B_P4Back'],
                BTN['C_P4HDMI'], BTN['C_P4Share'], BTN['C_P4PwrOn'], BTN['C_P4PwrOff'], BTN['C_P4Up'], BTN['C_P4Stop'], BTN['C_P4Down'], BTN['C_P4Back'],
                BTN['M_P4HDMI'], BTN['M_P4Share'], BTN['M_P4PwrOn'], BTN['M_P4PwrOff'], BTN['M_P4Up'], BTN['M_P4Stop'], BTN['M_P4Down'], BTN['M_P4Back']],

    ## Video Full Global Mode
    'VideoFG': [BTN['A_PMHDMI'], BTN['A_PMShare'], BTN['A_PMUp'], BTN['A_PMStop'], BTN['A_PMDown'], BTN['A_PMBack'],
                BTN['B_PMHDMI'], BTN['B_PMShare'], BTN['B_PMUp'], BTN['B_PMStop'], BTN['B_PMDown'], BTN['B_PMBack'],
                BTN['C_PMHDMI'], BTN['C_PMShare'], BTN['C_PMUp'], BTN['C_PMStop'], BTN['C_PMDown'], BTN['C_PMBack'],
                BTN['M_PMHDMI'], BTN['M_PMShare'], BTN['M_PMUp'], BTN['M_PMStop'], BTN['M_PMDown'], BTN['M_PMBack']],

    'Audio' : [BTN['A_VolLess'], BTN['A_VolPlus'], BTN['A_Mute'],
               BTN['B_VolLess'], BTN['B_VolPlus'], BTN['B_Mute'],
               BTN['C_VolLess'], BTN['C_VolPlus'], BTN['C_Mute']],
    
    ## Audio Full Global Mode
    'AudioF' : [BTN['A_.HDMI'], BTN['A_.Share'], BTN['A_.VolLess'], BTN['A_.VolPlus'], BTN['A_.MuteSpk'], BTN['A_.MuteMiM'], BTN['A_.MuteMiT'],
                BTN['B_.HDMI'], BTN['B_.Share'], BTN['B_.VolLess'], BTN['B_.VolPlus'], BTN['B_.MuteSpk'], BTN['B_.MuteMiM'], BTN['B_.MuteMiT'],
                BTN['C_.HDMI'], BTN['C_.Share'], BTN['C_.VolLess'], BTN['C_.VolPlus'], BTN['C_.MuteSpk'], BTN['C_.MuteMiM'], BTN['C_.MuteMiT'],
                BTN['M_.HDMI'], BTN['M_.Share'], BTN['M_.VolLess'], BTN['M_.VolPlus'], BTN['M_.MuteSpk'], BTN['M_.MuteMiM'], BTN['M_.MuteMiT']],

    'Lights': [BTN['A_Light1'], BTN['A_Light2'], BTN['A_Light3'], BTN['A_Light4'], BTN['A_BUp'], BTN['A_BStop'], BTN['A_BDown'],
               BTN['B_Light1'], BTN['B_Light2'], BTN['B_Light3'], BTN['B_Light4'], BTN['B_BUp'], BTN['B_BStop'], BTN['B_BDown'],
               BTN['C_Light1'], BTN['C_Light2'], BTN['C_Light3'], BTN['C_Light4'], BTN['C_BUp'], BTN['C_BStop'], BTN['C_BDown']],
    
    'Power' : [BTN['A_PwrAll'], BTN['B_PwrAll'], BTN['C_PwrAll']],
}

# UI Group Page Buttons
BTNGROUP = {
    'Room'     : MESet(BTNPAGE['Room']),

    'MainA'    : MESet([BTN['A_Video'], BTN['A_Audio'], BTN['A_Lights'], BTN['A_PwrOff']]),
    'MainB'    : MESet([BTN['B_Video'], BTN['B_Audio'], BTN['B_Lights'], BTN['B_PwrOff']]),
    'MainC'    : MESet([BTN['C_Video'], BTN['C_Audio'], BTN['C_Lights'], BTN['C_PwrOff']]),

    'MainFA'   : MESet([BTN['A_FVideo'], BTN['A_FAudio'], BTN['A_FLights'], BTN['A_VoIP'], BTN['A_FPwrOff']]),
    'MainFB'   : MESet([BTN['B_FVideo'], BTN['B_FAudio'], BTN['B_FLights'], BTN['B_VoIP'], BTN['B_FPwrOff']]),
    'MainFC'   : MESet([BTN['C_FVideo'], BTN['C_FAudio'], BTN['C_FLights'], BTN['C_VoIP'], BTN['C_FPwrOff']]),
    'MainFM'   : MESet([BTN['M_FVideo'], BTN['M_FAudio'], BTN['M_FLights'], BTN['M_VoIP'], BTN['M_FPwrOff']]),
}

# UI Button states
BTNSTATE = {
    'List' : ['Pressed', 'Released', 'Held', 'Repeated', 'Tapped']
}

# UI Labels
LBL = {
    ## PANEL M ----------------------------------------
    'M_Index'       : Label(TLPM, 2),
    'M_Room'        : Label(TLPM, 21),
    'M_PwrAll'      : Label(TLPM, 62),
    'M_CountAll'    : Label(TLPM, 63),
    'M_RoomFull'    : Label(TLPM, 121),
    'M_ABCPwrAll'   : Label(TLPM, 302),
    'M_ABCCountAll' : Label(TLPM, 303),
    'M_PIN'         : Label(TLPM, 1012),

    ## PANEL A ----------------------------------------
    'A_Index'       : Label(TLP1, 2),
    'A_Room'        : Label(TLP1, 21),
    'A_PwrAll'      : Label(TLP1, 62),
    'A_CountAll'    : Label(TLP1, 63),
    'A_RoomFull'    : Label(TLP1, 121),
    'A_ABCPwrAll'   : Label(TLP1, 302),
    'A_ABCCountAll' : Label(TLP1, 303),
    'A_PIN'         : Label(TLP1, 1012),

    ## PANEL B ----------------------------------------
    'B_Index'       : Label(TLP2, 2),
    'B_Room'        : Label(TLP2, 21),
    'B_PwrAll'      : Label(TLP2, 62),
    'B_CountAll'    : Label(TLP2, 63),
    'B_RoomFull'    : Label(TLP2, 121),
    'B_ABCPwrAll'   : Label(TLP2, 302),
    'B_ABCCountAll' : Label(TLP2, 303),
    'B_PIN'         : Label(TLP2, 1012),

    ## PANEL C ----------------------------------------
    'C_Index'       : Label(TLP3, 2),
    'C_Room'        : Label(TLP3, 21),
    'C_PwrAll'      : Label(TLP3, 62),
    'C_CountAll'    : Label(TLP3, 63),
    'C_RoomFull'    : Label(TLP3, 121),
    'C_ABCPwrAll'   : Label(TLP3, 302),
    'C_ABCCountAll' : Label(TLP3, 303),
    'C_PIN'         : Label(TLP3, 1012),
}

# UI Levels
LVL = {
    ## PANEL M ----------------------------------------
    'M_Room'    : Level(TLPM, 44),
    'M_AllRoom' : Level(TLPM, 207),
    ## PANEL A ----------------------------------------
    'M_Room'    : Level(TLP1, 44),
    'M_AllRoom' : Level(TLP1, 207),
    ## PANEL B ----------------------------------------
    'M_Room'    : Level(TLP2, 44),
    'M_AllRoom' : Level(TLP2, 207),
    ## PANEL C ----------------------------------------
    'M_Room'    : Level(TLP3, 44),
    'M_AllRoom' : Level(TLP3, 207),
}

POPUP = {
}

PAGE = {
}
